[General]
bypass-system = true
ipv6 = false
dns-server = https://dns.google/dns-query
hijack-dns = :53
update-url = https://raw.githubusercontent.com/givihub/ShadowRocket/main/givix.conf

[Rule]
GEOIP,RU,DIRECT
DOMAIN-SUFFIX,ru,DIRECT
DOMAIN-SUFFIX,рф,DIRECT
FINAL,PROXY
